**Arewa Data Science Academy**

Deep Learning Cohort2.0

Name: Abdullahi Sani Atiku

Email: abdullahisaniatiku@gmail.com

Title: Week 1 Solution



Exercises Solution

In [ ]:
# Exercise 2 - Solution

# Import torch
import torch

# Create random tensor
tensor1 = torch.rand(7, 7)

In [ ]:
# Exercise 3 - Solution

# Create another random tensor
tensor2 = torch.rand(1, 7)

# Transpose the second tensor to make its shape (7, 1)
tensor2_transposed = tensor2.T

# Perform matrix multiplication
torch.matmul(tensor1, tensor2_transposed)

tensor([[1.6914],
        [1.7581],
        [2.0906],
        [1.8975],
        [1.7585],
        [1.7961],
        [1.8900]])

In [ ]:
# Exercise 4 - Solution

# Set manual seed
torch.manual_seed(0)


# Create two random tensors
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)

# Transpose the second tensor to make its shape (7, 1)
tensor2_transposed = tensor2.T

# Matrix multiply tensors
result = torch.matmul(tensor1, tensor2_transposed)
print(result, result.shape)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


In [ ]:
# Exercise 5 - Solution

# Check if a GPU is available
if torch.cuda.is_available():
    # Set the GPU random seed
    torch.cuda.manual_seed(1234)

In [ ]:
# Exercise 6 - Solution

# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
tensor1 = torch.rand(2, 3, device=device)
tensor2 = torch.rand(2, 3, device=device)

In [ ]:
# Exercise 7 - Solution

# Transpose tensor2 to make its shape (3, 2)
tensor2_transposed = tensor2.T

# Perform matrix multiplication
result = torch.matmul(tensor1, tensor2_transposed)

# Output the result and its shape
print(result, result.shape)


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]]) torch.Size([2, 2])


In [ ]:
# Exercise 8 - Solution

# Find max
max_value = torch.max(result)

# Find min
min_value = torch.min(result)

In [ ]:
# Exercise 9 - Solution

# Find arg max
max_index = torch.argmax(result)

# Find arg min
min_index = torch.argmin(result)

In [ ]:
# Exercise 10 - Solution

# Set seed
torch.manual_seed(7)

# Create random tensor
tensor1 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor2 = tensor1.squeeze()

# Print out tensors and their shapes
print(tensor1)
print(tensor1.shape)
print(tensor2)
print(tensor2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
